### ISSUE TITLE
[Bug] Obfuscate is having trouble parsing some characters?

### ISSUE THREAD

**Issue by suchermon** [cehdeti/pyeti#11]
https://github.com/cehdeti/pyeti/blob/7f239a8945fa43a7f3f78063e63aa9fa09829953/pyeti/eti_django/templatetags/email.py#L12

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/21044824/153514606-38d92def-ede9-41a2-9707-4556f654f9e8.png">

**Comment by theunraveler** [comment]
In your template, `h31lo@world.comm` is interpreted as a variable named `h31lo@world.comm`, not the string `"h31lo@world.comm"`. If you want to obfuscate the string `"h31lo@world.comm"`, you'd need to do this:

```
{{ "h31lo@world.comm"|obfuscate_email }}
```
